# https://gohugo.io/getting-started/configuration/
baseURL: http://noynkd.github.io/

languageCode: ja-JP
hasCJKLanguage: true
timeZone: Asia/Tokyo

title: ざっき
theme:
- hugo-notice
- PaperMod
pagenate: 5

params:
  homeInfoParams:
    title: ざっき
    content: なんかあったときにメモする
  showBreadCrumbs: true
  showCodeCopyButtons: true
  hideSummary: false
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

ignoreFiles:
- README.md

menu:
  main:
  - identifier: posts
    name: Posts
    url: /posts/
    weight: 1
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 2
  - identifier: search
    name: Search
    url: /search/
    weight: 3

outputs:
  home:
  - HTML
  - RSS
  - JSON
