# https://gohugo.io/getting-started/configuration/
baseURL: http://noynkd.github.io/

languageCode: ja-JP
defaultContentLanguage: ja
hasCJKLanguage: true
timeZone: Asia/Tokyo

title: ざっき
theme:
- hugo-notice
- PaperMod
pagenate: 5

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: true
      unsafe: true
      xhtml: false

params:
  cover:
    responsiveInages: true
    linkFullImages: false
  homeInfoParams:
    title: ざっき
    content: >
      - なんかあったときにメモする
  showCodeCopyButtons: true
  hideSummary: false
  hideMeta: false
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

ignoreFiles:
- README.md

menu:
  main:
  - identifier: archives
    name: Archives
    url: /archives/
    weight: 1
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 2
  - identifier: search
    name: Search
    url: /search/
    weight: 3

outputs:
  home:
  - HTML
  - RSS
  - JSON
